FROM phusion/passenger-ruby22:0.9.15

# Set correct environment variables.
ENV HOME /root

# Use baseimage-docker's init process.
CMD ["/sbin/my_init"]

# Postgres backup
# RUN gem install backup -v 4.3.1

# Setup cron for periodic tasks
ADD docker/ops/cronfile /home/app/cronfile
RUN crontab /home/app/cronfile

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
