FROM phusion/passenger-ruby22:0.9.15

# Set correct environment variables.
ENV HOME /root
ENV APP_HOME /home/app/webapp

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

ENV BUNDLE_PATH /home/app/webapp/vendor/bundle
RUN npm -g install bower@1.7.9

ADD docker/my_init.d/*dev* /etc/my_init.d/
RUN chmod +x /etc/my_init.d/*dev*

WORKDIR /home/app/webapp/
ADD . /home/app/webapp/
RUN sudo chown -R app:app /home/app/webapp/

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/[!bundle]* /var/tmp/*
