FROM phusion/passenger-ruby22:0.9.15

# Set correct environment variables.
ENV HOME /root
ENV APP_HOME /home/app/webapp
ENV BUNDLE_PATH /home/app/webapp/vendor/bundle

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# Workdir
WORKDIR /home/app/webapp/

# PG Client for ops container
RUN apt-get update && apt-get install -y postgresql-client-9.3

# Backups for ops container
RUN gem install backup -v 4.2.3

# Install bower globally
RUN npm -g install bower@1.7.9

# Add files
ADD . /home/app/webapp/

# Change /home/app/webapp owner to user app
RUN sudo chown -R app:app /home/app/webapp/

# Add init script
ADD docker/my_init.d/*.sh /etc/my_init.d/
RUN chmod +x /etc/my_init.d/*.sh

# Clean up APT when done
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /var/tmp/*
